/* The following code was generated by JFlex 1.6.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int IN_COMMENT = 6;
  public static final int END_L_COMMENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  2,  2,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\12\1\12\1\1\22\0\1\3\1\56\1\53"+
    "\3\6\1\55\1\13\1\45\1\46\1\44\1\42\1\6\1\43\1\6"+
    "\1\11\1\10\11\5\1\31\1\41\1\6\1\40\3\6\5\4\1\33"+
    "\15\4\1\32\1\4\1\4\4\4\1\51\1\6\1\52\1\6\1\7"+
    "\1\6\1\26\1\34\1\35\1\30\1\20\1\15\1\4\1\17\1\14"+
    "\2\4\1\22\1\4\1\21\1\24\1\27\1\36\1\25\1\23\1\16"+
    "\1\4\1\37\4\4\1\47\1\54\1\50\1\6\6\0\1\12\u1fa2\0"+
    "\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\2\4\1\5\1\1\12\3"+
    "\1\6\1\7\1\10\3\3\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\2\1\1\25\4\0\1\26\1\3\1\27\10\3\1\30"+
    "\5\3\1\31\3\3\1\32\1\33\4\34\2\35\1\36"+
    "\1\37\1\3\1\40\2\3\1\41\2\3\1\42\1\3"+
    "\1\43\10\3\1\44\1\45\1\46\1\47\1\50\2\3"+
    "\1\51\1\52\1\53\1\54\1\55\1\3\1\56\1\57"+
    "\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\215\0\353\0\u011a"+
    "\0\u0149\0\215\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\215\0\353\0\353"+
    "\0\u037d\0\u03ac\0\u03db\0\215\0\215\0\215\0\215\0\215"+
    "\0\215\0\215\0\215\0\215\0\215\0\215\0\215\0\u040a"+
    "\0\u0439\0\215\0\u0468\0\u0497\0\u04c6\0\u04f5\0\353\0\u0524"+
    "\0\353\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\353\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\353"+
    "\0\u07b6\0\u07e5\0\u0814\0\215\0\215\0\u0843\0\215\0\u0872"+
    "\0\u08a1\0\u08d0\0\215\0\215\0\353\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\353\0\u09bb\0\u09ea\0\353\0\u0a19\0\353\0\u0a48"+
    "\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\353"+
    "\0\353\0\353\0\353\0\353\0\u0bc0\0\u0bef\0\353\0\353"+
    "\0\353\0\353\0\353\0\u0c1e\0\353\0\353\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\2\4\1\11\1\12"+
    "\1\4\1\13\1\14\1\15\1\16\1\7\1\17\2\7"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\7\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\53\4\1\47\62\4\61\0"+
    "\1\6\60\0\2\7\1\0\2\7\3\0\15\7\1\0"+
    "\6\7\17\0\1\53\2\0\2\53\1\10\1\53\1\54"+
    "\1\10\1\55\1\0\45\53\2\0\4\53\1\54\1\53"+
    "\1\55\1\0\44\53\4\0\5\56\2\0\44\56\4\0"+
    "\2\7\1\0\2\7\3\0\1\7\1\57\3\7\1\60"+
    "\7\7\1\0\6\7\23\0\2\7\1\0\2\7\3\0"+
    "\1\61\5\7\1\62\1\7\1\63\3\7\1\64\1\0"+
    "\6\7\23\0\2\7\1\0\2\7\3\0\3\7\1\65"+
    "\4\7\1\66\3\7\1\67\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\6\7\1\70\6\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\4\7\1\71\10\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\14\7"+
    "\1\72\1\0\6\7\23\0\2\7\1\0\2\7\3\0"+
    "\4\7\1\73\5\7\1\74\2\7\1\0\6\7\23\0"+
    "\2\7\1\0\2\7\3\0\6\7\1\75\6\7\1\0"+
    "\6\7\23\0\2\7\1\0\2\7\3\0\11\7\1\76"+
    "\3\7\1\0\6\7\23\0\2\7\1\0\2\7\3\0"+
    "\1\77\7\7\1\100\4\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\10\7\1\101\4\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\3\7\1\102\11\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\10\7"+
    "\1\103\4\7\1\0\6\7\73\0\1\104\57\0\1\105"+
    "\6\0\1\106\2\0\1\107\53\0\1\110\2\0\1\111"+
    "\53\0\1\112\2\0\1\113\61\0\1\114\47\0\2\7"+
    "\1\0\2\7\3\0\2\7\1\115\12\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\10\7\1\116\4\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\11\7"+
    "\1\117\3\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\4\7\1\120\10\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\4\7\1\121\10\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\13\7\1\122\1\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\4\7"+
    "\1\123\10\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\7\7\1\124\5\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\15\7\1\0\4\7\1\125\1\7"+
    "\23\0\2\7\1\0\2\7\3\0\12\7\1\126\2\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\2\7"+
    "\1\127\12\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\1\130\14\7\1\0\6\7\23\0\2\7\1\0"+
    "\2\7\3\0\1\131\14\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\15\7\1\0\3\7\1\132\2\7"+
    "\23\0\2\7\1\0\2\7\3\0\10\7\1\133\4\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\12\7"+
    "\1\134\2\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\1\135\14\7\1\0\6\7\24\0\1\106\2\0"+
    "\1\106\53\0\1\110\2\0\1\110\1\55\56\0\1\55"+
    "\52\0\1\112\2\0\1\112\52\0\2\7\1\0\2\7"+
    "\3\0\12\7\1\136\2\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\12\7\1\137\2\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\1\7\1\140\13\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\5\7"+
    "\1\141\7\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\1\7\1\142\13\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\4\7\1\143\10\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\14\7\1\144\1\0"+
    "\6\7\23\0\2\7\1\0\2\7\3\0\12\7\1\145"+
    "\2\7\1\0\6\7\23\0\2\7\1\0\2\7\3\0"+
    "\5\7\1\146\7\7\1\0\6\7\23\0\2\7\1\0"+
    "\2\7\3\0\2\7\1\147\12\7\1\0\6\7\23\0"+
    "\2\7\1\0\2\7\3\0\6\7\1\150\6\7\1\0"+
    "\6\7\23\0\2\7\1\0\2\7\3\0\11\7\1\151"+
    "\3\7\1\0\6\7\23\0\2\7\1\0\2\7\3\0"+
    "\14\7\1\152\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\2\7\1\153\12\7\1\0\6\7\23\0\2\7"+
    "\1\0\2\7\3\0\6\7\1\154\6\7\1\0\6\7"+
    "\23\0\2\7\1\0\2\7\3\0\7\7\1\155\5\7"+
    "\1\0\6\7\23\0\2\7\1\0\2\7\3\0\2\7"+
    "\1\156\12\7\1\0\6\7\23\0\2\7\1\0\2\7"+
    "\3\0\6\7\1\157\6\7\1\0\6\7\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3149];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\3\1\1\11\13\1\1\11"+
    "\5\1\14\11\2\1\1\11\4\0\25\1\2\11\1\1"+
    "\1\11\3\1\2\11\43\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private boolean debug_mode;
  public  boolean debug()            { return debug_mode; }
  public  void    debug(boolean mode){ debug_mode = mode; }

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [114] { System.out.println(\"file:\" + (yyline+1) +"+ZZ_NL+"    \":0: Error: Invalid input \'\" + yytext()+\"\'\");"+ZZ_NL+"  return symbol(sym.BADCHAR); }");
          { System.out.println("file:" + (yyline+1) +
    ":0: Error: Invalid input '" + yytext()+"'");
  return symbol(sym.BADCHAR);
          }
        case 49: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [87] { /* do nothing */ }");
          { /* do nothing */
          }
        case 50: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [107] { return symbol(sym.IDENTIFIER, yytext()); }");
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 51: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [59] { return symbol(sym.INTEGER,"+ZZ_NL+"                    Integer.parseInt(yytext())); }");
          { return symbol(sym.INTEGER,
                    Integer.parseInt(yytext()));
          }
        case 52: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [93] { return symbol(sym.DIV); }");
          { return symbol(sym.DIV);
          }
        case 53: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [52] { return symbol(sym.COLON); }");
          { return symbol(sym.COLON);
          }
        case 54: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [69] { return symbol(sym.T); }");
          { return symbol(sym.T);
          }
        case 55: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [70] { return symbol(sym.F); }");
          { return symbol(sym.F);
          }
        case 56: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [88] { return symbol(sym.ASSIGNMENT); }");
          { return symbol(sym.ASSIGNMENT);
          }
        case 57: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [89] { return symbol(sym.SEMICOL); }");
          { return symbol(sym.SEMICOL);
          }
        case 58: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [90] { return symbol(sym.PLUS); }");
          { return symbol(sym.PLUS);
          }
        case 59: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [91] { return symbol(sym.MINUS); }");
          { return symbol(sym.MINUS);
          }
        case 60: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [92] { return symbol(sym.MULT); }");
          { return symbol(sym.MULT);
          }
        case 61: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [96] { return symbol(sym.LPAREN); }");
          { return symbol(sym.LPAREN);
          }
        case 62: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [97] { return symbol(sym.RPAREN); }");
          { return symbol(sym.RPAREN);
          }
        case 63: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [98] { return symbol(sym.LBRACE); }");
          { return symbol(sym.LBRACE);
          }
        case 64: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [99] { return symbol(sym.RBRACE); }");
          { return symbol(sym.RBRACE);
          }
        case 65: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [100] { return symbol(sym.LBRACKET); }");
          { return symbol(sym.LBRACKET);
          }
        case 66: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [101] { return symbol(sym.RBRACKET); }");
          { return symbol(sym.RBRACKET);
          }
        case 67: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [102] { return symbol(sym.STRINGTERM); }");
          { return symbol(sym.STRINGTERM);
          }
        case 68: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [105] { return symbol(sym.NOT); }");
          { return symbol(sym.NOT);
          }
        case 69: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [42] { return symbol(sym.IF); }");
          { return symbol(sym.IF);
          }
        case 70: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [43] { return symbol(sym.FI); }");
          { return symbol(sym.FI);
          }
        case 71: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [51] { return symbol(sym.OD); }");
          { return symbol(sym.OD);
          }
        case 72: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [50] { return symbol(sym.DO); }");
          { return symbol(sym.DO);
          }
        case 73: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [103] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 74: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [104] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 75: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [61] { return symbol(sym.FLOAT); }");
          { return symbol(sym.FLOAT);
          }
        case 76: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [58] { return symbol(sym.RATIONAL); }");
          { return symbol(sym.RATIONAL);
          }
        case 77: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [63] { return symbol("+ZZ_NL+"                      sym.CHAR,"+ZZ_NL+"                      yytext()); }");
          { return symbol(
                      sym.CHAR,
                      yytext());
          }
        case 78: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [80] { return symbol(sym.INT_T); }");
          { return symbol(sym.INT_T);
          }
        case 79: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [46] { return symbol(sym.FOR); }");
          { return symbol(sym.FOR);
          }
        case 80: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [84] { return symbol(sym.TOP); }");
          { return symbol(sym.TOP);
          }
        case 81: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [82] { return symbol(sym.SEQ_T); }");
          { return symbol(sym.SEQ_T);
          }
        case 82: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [81] { return symbol(sym.RATIONAL_T); }");
          { return symbol(sym.RATIONAL_T);
          }
        case 83: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [55] { return symbol(sym.FDEF); }");
          { return symbol(sym.FDEF);
          }
        case 84: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [44] { return symbol(sym.THEN); }");
          { return symbol(sym.THEN);
          }
        case 85: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [56] { return symbol(sym.TDEF); }");
          { return symbol(sym.TDEF);
          }
        case 86: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [45] { return symbol(sym.ELSE); }");
          { return symbol(sym.ELSE);
          }
        case 87: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [49] { return symbol(sym.READ); }");
          { return symbol(sym.READ);
          }
        case 88: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [78] { return symbol(sym.DICT_T); }");
          { return symbol(sym.DICT_T);
          }
        case 89: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [76] { return symbol(sym.BOOLEAN_T); }");
          { return symbol(sym.BOOLEAN_T);
          }
        case 90: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [77] { return symbol(sym.CHAR_T); }");
          { return symbol(sym.CHAR_T);
          }
        case 91: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [83] { return symbol(sym.VOID_T); }");
          { return symbol(sym.VOID_T);
          }
        case 92: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [79] { return symbol(sym.FLOAT_T); }");
          { return symbol(sym.FLOAT_T);
          }
        case 93: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [71] { return symbol(sym.ALIAS); }");
          { return symbol(sym.ALIAS);
          }
        case 94: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [48] { return symbol(sym.PRINT); }");
          { return symbol(sym.PRINT);
          }
        case 95: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [47] { return symbol(sym.FORALL); }");
          { return symbol(sym.FORALL);
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
