/* The following code was generated by JFlex 1.6.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\2\0\1\1\22\0\1\3\1\56\1\17\3\10"+
    "\1\57\1\15\1\60\1\61\1\54\1\52\1\31\1\53\1\14\1\13"+
    "\1\12\11\7\1\32\1\63\1\25\1\51\1\26\2\10\5\5\1\6"+
    "\15\5\1\6\1\5\1\5\4\5\1\23\1\16\1\24\1\55\1\11"+
    "\1\10\1\42\1\36\1\40\1\44\1\21\1\46\1\5\1\41\1\45"+
    "\2\5\1\37\1\62\1\47\1\34\1\35\1\22\1\43\1\20\1\33"+
    "\1\65\1\50\1\64\3\5\1\27\1\4\1\30\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\2\2\4\1\5\1\6"+
    "\1\0\1\7\2\3\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\14\3\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\0\1\26\1\27\1\3\1\30\1\3"+
    "\1\31\1\0\1\32\1\33\4\0\2\3\1\34\1\35"+
    "\3\3\1\36\7\3\1\37\1\3\1\40\1\41\3\3"+
    "\1\42\1\3\1\43\1\44\1\45\2\3\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\2\0\2\56"+
    "\1\57\1\60\1\61\2\3\1\62\4\3\1\63\4\3"+
    "\1\64\1\3\1\65\6\3\1\66\1\67\1\70\1\71"+
    "\1\3\1\72\1\73\2\3\1\74\1\75\2\3\1\76"+
    "\1\77\1\100\1\3\1\101\1\102\2\3\1\103\1\104"+
    "\1\105\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u010e\0\u0144"+
    "\0\u017a\0\242\0\242\0\u01b0\0\242\0\u01e6\0\u021c\0\242"+
    "\0\242\0\u0252\0\242\0\242\0\242\0\242\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e"+
    "\0\u04a4\0\u04da\0\u0510\0\u0546\0\242\0\242\0\242\0\242"+
    "\0\u057c\0\u05b2\0\242\0\242\0\u05e8\0\242\0\u061e\0\u0654"+
    "\0\u068a\0\242\0\242\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798"+
    "\0\u07ce\0\242\0\242\0\u0804\0\u083a\0\u0870\0\u010e\0\u08a6"+
    "\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u010e\0\u0a20"+
    "\0\u010e\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u010e\0\u0b2e\0\242"+
    "\0\242\0\242\0\u0b64\0\u0b9a\0\242\0\242\0\242\0\242"+
    "\0\242\0\242\0\242\0\242\0\u0bd0\0\u0c06\0\u0c3c\0\242"+
    "\0\u072c\0\242\0\u010e\0\u0c72\0\u0ca8\0\u010e\0\u0cde\0\u0d14"+
    "\0\u0d4a\0\u0d80\0\u010e\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u010e"+
    "\0\u0e8e\0\u010e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u1008\0\u010e\0\u010e\0\u103e"+
    "\0\u1074\0\u010e\0\u010e\0\u10aa\0\u10e0\0\u010e\0\u010e\0\u010e"+
    "\0\u1116\0\u010e\0\u010e\0\u114c\0\u1182\0\u010e\0\u010e\0\u010e"+
    "\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\2\4\1\5\1\6\1\7\1\10\2\0"+
    "\1\11\1\12\1\13\1\14\1\0\1\15\1\16\1\17"+
    "\1\6\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\6"+
    "\1\36\1\37\1\40\1\41\1\42\1\6\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\6\1\60\2\0\13\60\1\61"+
    "\1\62\46\60\2\0\1\4\155\0\1\63\66\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\16\6\11\0\1\6"+
    "\1\0\2\6\7\0\1\10\1\0\1\64\1\10\1\65"+
    "\1\66\62\0\1\64\1\0\1\65\1\66\55\0\7\67"+
    "\1\0\52\67\5\0\3\6\1\0\2\6\5\0\1\6"+
    "\1\70\1\6\10\0\16\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\4\6"+
    "\1\71\11\6\11\0\1\6\1\0\2\6\51\0\1\72"+
    "\46\0\1\73\40\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\1\6\1\74\4\6\1\75\2\6\1\76\4\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\11\6\1\77\4\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\10\6\1\100\5\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\1\6"+
    "\1\101\14\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\1\6\1\102\1\6\10\0\16\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\6\6\1\103\7\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\4\6\1\104\11\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\1\6\1\105\1\6"+
    "\10\0\7\6\1\106\6\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\1\6"+
    "\1\107\10\6\1\110\3\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\13\6"+
    "\1\111\1\112\1\6\11\0\1\6\1\0\2\6\5\0"+
    "\3\6\1\0\2\6\5\0\3\6\10\0\1\6\1\113"+
    "\2\6\1\114\4\6\1\115\1\116\3\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\1\6\1\117\14\6\11\0\1\6\1\0\2\6"+
    "\51\0\1\120\65\0\1\121\73\0\1\122\13\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\7\6\1\123\6\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\6\6\1\124\7\6\11\0\1\6"+
    "\1\0\2\6\1\60\2\0\13\60\2\0\46\60\15\0"+
    "\1\125\1\126\1\127\13\0\1\130\2\0\1\131\4\0"+
    "\1\132\2\0\1\133\1\134\25\0\1\135\2\0\1\136"+
    "\62\0\1\137\2\0\1\140\62\0\1\141\2\0\1\141"+
    "\70\0\1\142\55\0\3\6\1\0\2\6\5\0\2\6"+
    "\1\143\10\0\16\6\11\0\1\6\1\0\2\6\5\0"+
    "\3\6\1\0\2\6\5\0\1\144\2\6\10\0\12\6"+
    "\1\145\3\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\2\6\1\146\13\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\1\6\1\147\1\6\10\0\16\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\1\6"+
    "\1\150\1\6\10\0\16\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\12\6"+
    "\1\151\3\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\1\6\1\152\14\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\14\6\1\153\1\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\7\6\1\154\6\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\12\6"+
    "\1\155\3\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\1\156\6\6\1\157"+
    "\6\6\11\0\1\6\1\0\2\6\5\0\3\6\1\0"+
    "\2\6\5\0\3\6\10\0\1\160\15\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\5\6\1\161\10\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\1\162"+
    "\15\6\11\0\1\6\1\0\2\6\5\0\3\6\1\0"+
    "\2\6\5\0\3\6\10\0\10\6\1\163\5\6\11\0"+
    "\1\6\1\0\2\6\5\0\3\6\1\0\2\6\5\0"+
    "\3\6\10\0\1\6\1\164\14\6\11\0\1\6\1\0"+
    "\2\6\5\0\3\6\1\0\2\6\5\0\1\6\1\165"+
    "\1\6\10\0\16\6\11\0\1\6\1\0\2\6\5\0"+
    "\3\6\1\0\2\6\5\0\3\6\10\0\12\6\1\166"+
    "\3\6\11\0\1\6\1\0\2\6\5\0\3\6\1\0"+
    "\2\6\5\0\3\6\10\0\12\6\1\167\3\6\11\0"+
    "\1\6\1\0\2\6\5\0\3\6\1\0\2\6\5\0"+
    "\3\6\10\0\12\6\1\170\3\6\11\0\1\6\1\0"+
    "\2\6\7\0\1\135\2\0\1\135\1\65\65\0\1\65"+
    "\61\0\1\137\2\0\1\137\60\0\3\6\1\0\2\6"+
    "\5\0\1\6\1\171\1\6\10\0\16\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\13\6\1\172\2\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\14\6"+
    "\1\173\1\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\13\6\1\174\2\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\14\6\1\175\1\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\4\6\1\176\11\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\10\6"+
    "\1\177\5\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\7\6\1\200\6\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\16\6\11\0\1\6\1\0\1\6"+
    "\1\201\5\0\3\6\1\0\2\6\5\0\3\6\10\0"+
    "\11\6\1\202\4\6\11\0\1\6\1\0\2\6\5\0"+
    "\3\6\1\0\2\6\5\0\3\6\10\0\1\203\15\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\7\6\1\204\6\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\7\6\1\205\6\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\13\6"+
    "\1\206\2\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\11\6\1\207\4\6"+
    "\11\0\1\6\1\0\2\6\5\0\3\6\1\0\2\6"+
    "\5\0\3\6\10\0\14\6\1\210\1\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\4\6\1\211\11\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\1\212"+
    "\15\6\11\0\1\6\1\0\2\6\5\0\3\6\1\0"+
    "\2\6\5\0\1\213\2\6\10\0\16\6\11\0\1\6"+
    "\1\0\2\6\5\0\3\6\1\0\2\6\5\0\3\6"+
    "\10\0\10\6\1\214\5\6\11\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\2\6\5\0\3\6\10\0\4\6"+
    "\1\215\11\6\11\0\1\6\1\0\2\6\5\0\3\6"+
    "\1\0\2\6\5\0\3\6\10\0\1\216\15\6\11\0"+
    "\1\6\1\0\2\6\5\0\3\6\1\0\2\6\5\0"+
    "\1\6\1\217\1\6\10\0\16\6\11\0\1\6\1\0"+
    "\2\6\5\0\3\6\1\0\2\6\5\0\3\6\10\0"+
    "\14\6\1\220\1\6\11\0\1\6\1\0\2\6\5\0"+
    "\3\6\1\0\2\6\5\0\3\6\10\0\4\6\1\221"+
    "\11\6\11\0\1\6\1\0\2\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4536];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\5\1\2\11\1\0\1\11\2\1"+
    "\2\11\1\1\4\11\16\1\4\11\1\1\1\0\2\11"+
    "\1\1\1\11\2\1\1\0\2\11\4\0\2\1\2\11"+
    "\24\1\3\11\2\1\10\11\2\0\1\1\1\11\1\1"+
    "\1\11\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private boolean debug_mode;
  public  boolean debug()            { return debug_mode; }
  public  void    debug(boolean mode){ debug_mode = mode; }
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [42] { /* do nothing */ }");
          { /* do nothing */
          }
        case 71: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [43] { return symbol(sym.BOOL); }");
          { return symbol(sym.BOOL);
          }
        case 72: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [117] { return symbol(sym.IDENTIFIER); }");
          { return symbol(sym.IDENTIFIER);
          }
        case 73: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [50] { return symbol(sym.INTEGER,"+ZZ_NL+"        Integer.parseInt(yytext())); }");
          { return symbol(sym.INTEGER,
        Integer.parseInt(yytext()));
          }
        case 74: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [82] { return symbol(sym.DIV); }");
          { return symbol(sym.DIV);
          }
        case 75: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [84] { return symbol(sym.DOT); }");
          { return symbol(sym.DOT);
          }
        case 76: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [54] { string.setLength(0);"+ZZ_NL+"    yybegin(STRING); }");
          { string.setLength(0);
    yybegin(STRING);
          }
        case 77: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [58] { return symbol(sym.LBRACKET); }");
          { return symbol(sym.LBRACKET);
          }
        case 78: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [59] { return symbol(sym.RBRACKET); }");
          { return symbol(sym.RBRACKET);
          }
        case 79: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [60] { return symbol(sym.LANGLE); }");
          { return symbol(sym.LANGLE);
          }
        case 80: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [61] { return symbol(sym.RANGLE); }");
          { return symbol(sym.RANGLE);
          }
        case 81: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [62] { return symbol(sym.LBRACE); }");
          { return symbol(sym.LBRACE);
          }
        case 82: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [63] { return symbol(sym.RBRACE); }");
          { return symbol(sym.RBRACE);
          }
        case 83: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [64] { return symbol(sym.COMMA); }");
          { return symbol(sym.COMMA);
          }
        case 84: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [65] { return symbol(sym.COLON); }");
          { return symbol(sym.COLON);
          }
        case 85: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [78] { return symbol(sym.ASSIGNMENT); }");
          { return symbol(sym.ASSIGNMENT);
          }
        case 86: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [79] { return symbol(sym.PLUS); }");
          { return symbol(sym.PLUS);
          }
        case 87: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [80] { return symbol(sym.MINUS); }");
          { return symbol(sym.MINUS);
          }
        case 88: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [81] { return symbol(sym.MULT); }");
          { return symbol(sym.MULT);
          }
        case 89: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [83] { return symbol(sym.POW); }");
          { return symbol(sym.POW);
          }
        case 90: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [93] { return symbol(sym.NOT); }");
          { return symbol(sym.NOT);
          }
        case 91: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [94] { return symbol(sym.LPAREN); }");
          { return symbol(sym.LPAREN);
          }
        case 92: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [95] { return symbol(sym.RPAREN); }");
          { return symbol(sym.RPAREN);
          }
        case 93: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [102] { return symbol(sym.SEMICOLON); }");
          { return symbol(sym.SEMICOLON);
          }
        case 94: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [124] { string.append(yytext()); }");
          { string.append(yytext());
          }
        case 95: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [121] { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL,"+ZZ_NL+"    string.toString()); }");
          { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL,
    string.toString());
          }
        case 96: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [91] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 97: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [90] { return symbol(sym.LTEQ); }");
          { return symbol(sym.LTEQ);
          }
        case 98: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [85] { return symbol(sym.APPEND); }");
          { return symbol(sym.APPEND);
          }
        case 99: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [111] { return symbol(sym.OD); }");
          { return symbol(sym.OD);
          }
        case 100: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [110] { return symbol(sym.DO); }");
          { return symbol(sym.DO);
          }
        case 101: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [103] { return symbol(sym.IF); }");
          { return symbol(sym.IF);
          }
        case 102: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [112] { return symbol(sym.IN); }");
          { return symbol(sym.IN);
          }
        case 103: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [107] { return symbol(sym.FI); }");
          { return symbol(sym.FI);
          }
        case 104: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [88] { return symbol(sym.EQ); }");
          { return symbol(sym.EQ);
          }
        case 105: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [89] { return symbol(sym.NEQ); }");
          { return symbol(sym.NEQ);
          }
        case 106: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [92] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 107: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [131] { string.append( \'\\\'\' ); }");
          { string.append( '\'' );
          }
        case 108: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [132] { string.append( \'\\\\\' ); }");
          { string.append( '\\' );
          }
        case 109: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [130] { string.append( \'\\\"\' ); }");
          { string.append( '\"' );
          }
        case 110: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [126] { string.append( \'\\t\' ); }");
          { string.append( '\t' );
          }
        case 111: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [125] { string.append( \'\\b\' ); }");
          { string.append( '\b' );
          }
        case 112: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [129] { string.append( \'\\r\' ); }");
          { string.append( '\r' );
          }
        case 113: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [128] { string.append( \'\\f\' ); }");
          { string.append( '\f' );
          }
        case 114: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [127] { string.append( \'\\n\' ); }");
          { string.append( '\n' );
          }
        case 115: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [52] { return symbol(sym.RATIONAL); }");
          { return symbol(sym.RATIONAL);
          }
        case 116: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [49] { return symbol(sym.FLOAT); }");
          { return symbol(sym.FLOAT);
          }
        case 117: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [44] { return symbol("+ZZ_NL+"                        sym.CHAR,"+ZZ_NL+"                        yytext()); }");
          { return symbol(
                        sym.CHAR,
                        yytext());
          }
        case 118: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [57] { return symbol(sym.SEQ_T); }");
          { return symbol(sym.SEQ_T);
          }
        case 119: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [68] { return symbol(sym.TOP_T); }");
          { return symbol(sym.TOP_T);
          }
        case 120: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [96] { return symbol(sym.LEN); }");
          { return symbol(sym.LEN);
          }
        case 121: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [74] { return symbol(sym.RATIONAL_T); }");
          { return symbol(sym.RATIONAL_T);
          }
        case 122: break;
        case 53: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [73] { return symbol(sym.INT_T); }");
          { return symbol(sym.INT_T);
          }
        case 123: break;
        case 54: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [105] { return symbol(sym.ELSE); }");
          { return symbol(sym.ELSE);
          }
        case 124: break;
        case 55: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [106] { return symbol(sym.ELIF); }");
          { return symbol(sym.ELIF);
          }
        case 125: break;
        case 56: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [104] { return symbol(sym.THEN); }");
          { return symbol(sym.THEN);
          }
        case 126: break;
        case 57: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [100] { return symbol(sym.TDEF); }");
          { return symbol(sym.TDEF);
          }
        case 127: break;
        case 58: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [69] { return symbol(sym.BOOLEAN_T); }");
          { return symbol(sym.BOOLEAN_T);
          }
        case 128: break;
        case 59: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [70] { return symbol(sym.CHAR_T); }");
          { return symbol(sym.CHAR_T);
          }
        case 129: break;
        case 60: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [115] { return symbol(sym.READ); }");
          { return symbol(sym.READ);
          }
        case 130: break;
        case 61: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [71] { return symbol(sym.DICT_T); }");
          { return symbol(sym.DICT_T);
          }
        case 131: break;
        case 62: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [99] { return symbol(sym.FDEF); }");
          { return symbol(sym.FDEF);
          }
        case 132: break;
        case 63: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [75] { return symbol(sym.VOID); }");
          { return symbol(sym.VOID);
          }
        case 133: break;
        case 64: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [98] { return symbol(sym.MAIN); }");
          { return symbol(sym.MAIN);
          }
        case 134: break;
        case 65: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [114] { return symbol(sym.PRINT); }");
          { return symbol(sym.PRINT);
          }
        case 135: break;
        case 66: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [101] { return symbol(sym.ALIAS); }");
          { return symbol(sym.ALIAS);
          }
        case 136: break;
        case 67: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [72] { return symbol(sym.FLOAT_T); }");
          { return symbol(sym.FLOAT_T);
          }
        case 137: break;
        case 68: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [108] { return symbol(sym.WHILE); }");
          { return symbol(sym.WHILE);
          }
        case 138: break;
        case 69: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [116] { return symbol(sym.RETURN); }");
          { return symbol(sym.RETURN);
          }
        case 139: break;
        case 70: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [109] { return symbol(sym.FORALL); }");
          { return symbol(sym.FORALL);
          }
        case 140: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
