
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 36;
  public static final int POW = 16;
  public static final int GTEQ = 58;
  public static final int STRING_LITERAL = 19;
  public static final int LBRACKET = 29;
  public static final int MULT = 14;
  public static final int CHAR = 21;
  public static final int LTEQ = 57;
  public static final int ASSIGNMENT = 55;
  public static final int T = 22;
  public static final int PERIOD = 52;
  public static final int CHAR_T = 3;
  public static final int INTEGER = 18;
  public static final int DICT_ = 4;
  public static final int LPAREN = 25;
  public static final int BADCHAR = 66;
  public static final int FOR = 35;
  public static final int MINUS = 13;
  public static final int F = 23;
  public static final int RPAREN = 26;
  public static final int TOP_T = 9;
  public static final int NOT = 64;
  public static final int AND = 63;
  public static final int SEMICOLON = 48;
  public static final int LT = 61;
  public static final int APPEND = 49;
  public static final int RATIONAL = 24;
  public static final int SEQ_T = 8;
  public static final int OR = 62;
  public static final int IN = 47;
  public static final int TDEF = 43;
  public static final int COMMA = 53;
  public static final int FI = 34;
  public static final int DIV = 15;
  public static final int INT_T = 6;
  public static final int PLUS = 12;
  public static final int MAIN = 65;
  public static final int IF = 33;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int OD = 32;
  public static final int RBRACKET = 30;
  public static final int error = 1;
  public static final int NEQ = 59;
  public static final int FDEF = 42;
  public static final int BOOLEAN_T = 2;
  public static final int EQ = 60;
  public static final int COLON = 46;
  public static final int ELSE = 38;
  public static final int LBRACE = 27;
  public static final int READ = 44;
  public static final int WHILE = 39;
  public static final int FLOAT = 17;
  public static final int THEN = 37;
  public static final int RBRACE = 28;
  public static final int FLOAT_T = 5;
  public static final int UNDERSCORE = 51;
  public static final int LEN = 54;
  public static final int ALIAS = 56;
  public static final int RATIONAL_T = 7;
  public static final int GT = 50;
  public static final int ELIF = 40;
  public static final int PRINT = 45;
  public static final int DO = 31;
  public static final int VOID_T = 10;
  public static final int DICT_T = 11;
  public static final int IDENTIFIER = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN_T",
  "CHAR_T",
  "DICT_",
  "FLOAT_T",
  "INT_T",
  "RATIONAL_T",
  "SEQ_T",
  "TOP_T",
  "VOID_T",
  "DICT_T",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "FLOAT",
  "INTEGER",
  "STRING_LITERAL",
  "IDENTIFIER",
  "CHAR",
  "T",
  "F",
  "RATIONAL",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "DO",
  "OD",
  "IF",
  "FI",
  "FOR",
  "FORALL",
  "THEN",
  "ELSE",
  "WHILE",
  "ELIF",
  "RETURN",
  "FDEF",
  "TDEF",
  "READ",
  "PRINT",
  "COLON",
  "IN",
  "SEMICOLON",
  "APPEND",
  "GT",
  "UNDERSCORE",
  "PERIOD",
  "COMMA",
  "LEN",
  "ASSIGNMENT",
  "ALIAS",
  "LTEQ",
  "GTEQ",
  "NEQ",
  "EQ",
  "LT",
  "OR",
  "AND",
  "NOT",
  "MAIN",
  "BADCHAR"
  };
}

